/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
import * as import0 from 'angular2/src/core/linker/debug_context';
import * as import1 from './test';
import * as import2 from 'angular2/src/core/render/api';
import * as import3 from 'angular2/src/core/linker/view';
import * as import4 from './app';
import * as import5 from 'angular2/src/core/linker/element';
import * as import6 from 'angular2/src/core/linker/view_utils';
import * as import7 from 'angular2/src/core/di/injector';
import * as import8 from 'angular2/src/core/linker/view_type';
import * as import9 from 'angular2/src/core/change_detection/change_detection';
import * as import10 from './test.ngfactory';
import * as import11 from 'angular2/src/core/metadata/view';
import * as import12 from 'angular2/src/core/linker/component_factory';
const styles_App:any[] = [];
const nodeDebugInfos_App0:import0.StaticNodeDebugInfo[] = [
  new import0.StaticNodeDebugInfo([],null,{}),
  new import0.StaticNodeDebugInfo([],null,{}),
  new import0.StaticNodeDebugInfo([],null,{}),
  new import0.StaticNodeDebugInfo([],null,{}),
  new import0.StaticNodeDebugInfo([import1.TestComponent],import1.TestComponent,{}),
  new import0.StaticNodeDebugInfo([],null,{})
]
;
var renderType_App:import2.RenderComponentType = null;
class _View_App0 extends import3.AppView<import4.App> {
  private _text_0: any;
  private _el_1: any;
  private _text_2: any;
  private _text_3: any;
  private _el_4: any;
  private _appEl_4:import5.AppElement;
  private _TestComponent_4_4:import1.TestComponent;
  private _text_5: any;
  private _expr_0: any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import5.AppElement) {
    super(_View_App0,renderType_App,import8.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import9.ChangeDetectionStrategy.CheckAlways,nodeDebugInfos_App0);
  }
  createInternal(rootSelector:string):import5.AppElement {
    const parentRenderNode = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n	  ',this.debug(0,0,0));
    this._el_1 = this.renderer.createElement(parentRenderNode,'div',this.debug(1,1,3));
    this._text_2 = this.renderer.createText(this._el_1,'',this.debug(2,1,8));
    this._text_3 = this.renderer.createText(parentRenderNode,'\n	  ',this.debug(3,1,28));
    this._el_4 = this.renderer.createElement(parentRenderNode,'test-component',this.debug(4,2,3));
    this._appEl_4 = new import5.AppElement(4,null,this,this._el_4);
    var compView_4 = import10.viewFactory_TestComponent0(this.viewUtils,this.injector(4),this._appEl_4);
    this._TestComponent_4_4 = new import1.TestComponent();
    this._appEl_4.initComponent(this._TestComponent_4_4,[],compView_4);
    compView_4.create(this._TestComponent_4_4,[],null);
    this._text_5 = this.renderer.createText(parentRenderNode,'\n	',this.debug(5,2,36));
    this._expr_0 = import9.uninitialized;
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._text_3,
      this._el_4,
      this._text_5
    ]
    ,[],[]);
    return null;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.TestComponent) && (4 === requestNodeIndex))) { return this._TestComponent_4_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    this.debug(2,1,8);
    const currVal_0 = import6.interpolate(1,'Hello ',this.context.name,'');
    if (import6.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_2,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_App0(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import5.AppElement):import3.AppView<import4.App> {
  if ((renderType_App === null)) { (renderType_App = viewUtils.createRenderComponentType('/Users/robwormald/Dev/demos/ng2-compiler-test2/src/app.ts',0,import11.ViewEncapsulation.None,styles_App)); }
  return new _View_App0(viewUtils,parentInjector,declarationEl);
}
const styles_App_Host:any[] = [];
const nodeDebugInfos_App_Host0:import0.StaticNodeDebugInfo[] = [new import0.StaticNodeDebugInfo([import4.App],import4.App,{})];
var renderType_App_Host:import2.RenderComponentType = null;
class _View_App_Host0 extends import3.AppView<any> {
  private _el_0: any;
  private _appEl_0:import5.AppElement;
  private _App_0_4:import4.App;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import5.AppElement) {
    super(_View_App_Host0,renderType_App_Host,import8.ViewType.HOST,viewUtils,parentInjector,declarationEl,import9.ChangeDetectionStrategy.CheckAlways,nodeDebugInfos_App_Host0);
  }
  createInternal(rootSelector:string):import5.AppElement {
    this._el_0 = this.selectOrCreateHostElement('test-app',rootSelector,this.debug(0,0,0));
    this._appEl_0 = new import5.AppElement(0,null,this,this._el_0);
    var compView_0 = viewFactory_App0(this.viewUtils,this.injector(0),this._appEl_0);
    this._App_0_4 = new import4.App();
    this._appEl_0.initComponent(this._App_0_4,[],compView_0);
    compView_0.create(this._App_0_4,this.projectableNodes,null);
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import4.App) && (0 === requestNodeIndex))) { return this._App_0_4; }
    return notFoundResult;
  }
}
function viewFactory_App_Host0(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import5.AppElement):import3.AppView<any> {
  if ((renderType_App_Host === null)) { (renderType_App_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.Emulated,styles_App_Host)); }
  return new _View_App_Host0(viewUtils,parentInjector,declarationEl);
}
export const AppNgFactory:import12.ComponentFactory = new import12.ComponentFactory('test-app',viewFactory_App_Host0,import4.App);